theme: jekyll-theme-minimal
title: Welcome to My Portfolio!
description: Hello! My name is Annika and I am currently learning Swift and the basics of app development! 
### [View My Work](ViewMyWork.md)

